version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    #command: gunicorn GerOndApp.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./staticfiles:/app/staticfiles
    ports:
      - "53900:8000"
    env_file:
      - dotenvfiles/.env
    restart: unless-stopped
